### ISSUE TITLE
Problems with (:assign var #\char)

### ISSUE THREAD

**Issue by jjkola** [vy/meta-sexp#1]
I was creating a syntax parser and because I haven't yet decided all things I was using dummy values in the syntax code.

So I  had the following code:

``` lisp
(defrule test (&aux param) ()
  (:or (:and (:icase "t") (:assign param #\t))
       (:and (:icase "r") (:assign param #\r)))
  (:return param))
```

When I called (test (create-parser-context "t")) I was baffled that why was the case failing even though it should not have (or at least I thought so).

After I reviewed the generated code I realized (well, I didn't immediately check that as I just tried experimenting with code to see why it was failing) that #\t was being transformed to a check even though what I wanted was to use the value as is. As it was kind of experimental code and I don't think I will use charcters in the production code this is not a problem to me but I thought I will write this down so that if others have same kind of problems they will be able resolve the case quicker.

**Comment by jjkola** [comment]
Similar problem happens also if you write:

``` lisp
(defrule logical-operator () ()
  (:or (:and "&" :and)
       (:and "|" :or)))
```

I wanted the atom the last :and and the last :or to be used as is but the parser generator transformed those to checks. This happens with any keyword which happens to be same as one of the directives. I think a literal rule should be in order, or something similar so that you can use "reserved" keywords, strings, and/or characters without the fear of them being incorrectly transformed. You could always hack around with the issue but I think this should be corrected in such way that if I happen to introduce a new keyword specializer that it won't cause bugs in previously perfectly working parser code.

**Comment by jjkola** [comment]
Here is a code for :literal directive which can be used for cases where the for example :and keyword is wishes to be used as is.

``` lisp
(defmethod transform-grammar
    (ret ctx (in-meta (eql t)) (directive (eql :literal)) &optional args)
  "\(:LITERAL FORM FORM)

Uses the provided forms as is without any transformation. Can be used for
\"reserved\" keywords, strings, chars, etc. If no arguments given returns
itself (.ie :literal). This way if you want to pass :literal you don't
need to say (:literal :literal)."
  (declare (ignore ret ctx))
  (cond ((and (consp args) (consp (cdr args))) `(list ,@args))
        ((consp args) (car args))
        (t :literal)))
```

**Comment by vy** [comment]
Hey @jjkola! Sorry for the late(!?!?!) response, for some reason I've totally missed this ticket. As you can imagine, it has been a long time (~10 years) since I lost touched the project. If you're still using meta-sexp, a PR for your `:literal` would be more then welcome.
