### ISSUE TITLE
Allow file-stream as input to create-parser-context

### ISSUE THREAD

**Issue by ghost** [vy/meta-sexp#2]
In practice, one would often want to parse files rather than strings. Restricting input type to jst `(or string string-stream)` makes it challenging to use `file-stream` (one would need to write a wrapper that shadows CL functions s.a. `read-char` to replace them with generic function by the same name...).  Even better, relax the requirement to just `input-stream`, so that `flexi-stream` would also work.

**Comment by vy** [comment]
I haven't been touching any Common Lisp code base since ten years. TBH, I would really appreciate a PR.

**Comment by ghost** [comment]
I'll see what I can do. I should have some time to invest into this.

**Comment by ghost** [comment]
Actually, I don't think it merits a PR :) All I ended up doing was replacing `string-stream` with `stream` and it just worked.

However, in long term, it would be interesting to explore a possibility to process any sequence, not necessarily a string.

**Comment by vy** [comment]
@wvxvw, I've pushed to change. Thanks for spending time on the issue.
